apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/black-dagger93/whoami.git
    targetRevision: HEAD
    path: devops/helm/whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami